// VARIABEL
const nama = "Budi"
// nama = "Andi" // ERROR TIDAK BISA RE ASSIGN (MENGGANTI) VALUE CONST

let skor = 0
// skor = 900 // VARIABEL LET MEMILIKI NILAI YANG FLEKSIBEL DAPAT DI RE ASSIGN
console.log(skor)

// TIPE DATA
const merekSepatu = "Adidas" // STRING (VARIABEL YANG MENAMPUNG NILAI KARAKTER DITANDAI DENGAN TANDA " " (PETIK))
const ukuran = 34 // INT, INTEGER, NUMBER (VARIABEL YANG MENAMPUNG NILAI ANGKA)
const longgar = false // BOOL, BOOLEAN (VARIABEL YANG MENAMPUNG NILAI TRUE/FALSE)
